FROM ruby:%%VERSION%%alpine
ADD Gemfile /app/
RUN apk --update add --virtual build-dependencies ruby-dev build-base && \
  gem install bundler --no-ri --no-rdoc && \
  cd /app ; bundle install --without development test && \
  apk del build-dependencies
ADD . /app
ENV RACK_ENV production
WORKDIR /app
CMD ["bundle", "exec", "ruby", "replr-bootstrap.rb"]
